apiVersion: v1
kind: "Template"
metadata:
  name: apiman-dev-build-template
  annotations:
    description: "Template for creating local builds of apiman components from source."
    tags: "infrastructure"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: origin
    name: origin
  spec:
    dockerImageRepository: openshift/origin:latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-elasticsearch
    name: centos
  spec:
    dockerImageRepository: library/centos:7
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-deployer
    name: apiman-deployer
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-elasticsearch
    name: apiman-elasticsearch
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-curator
    name: apiman-curator
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-deployer
    name: apiman-deployer
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-deployer:latest
    resources: {}
    source:
      contextDir: deployer
      git:
        uri: ${APIMAN_FORK_URL}
        ref: ${APIMAN_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: origin:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: apiman-elasticsearch
    name: apiman-elasticsearch
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-elasticsearch:latest
    resources: {}
    source:
      contextDir: elasticsearch
      git:
        uri: ${APIMAN_FORK_URL}
        ref: ${APIMAN_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:7
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-curator
    name: apiman-curator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-curator:latest
    resources: {}
    source:
      contextDir: curator
      git:
        uri: ${APIMAN_FORK_URL}
        ref: ${APIMAN_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: openshift/base-centos7
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
-
  description: 'URL for apiman fork'
  name: APIMAN_FORK_URL
  value: https://github.com/openshift/origin-apiman
-
  description: 'branch for origin-apiman fork'
  name: APIMAN_FORK_BRANCH
  value: master
